#!/bin/bash
# setup-omniqi.sh — Setup completo do Hermes-Agent Trader OmniQI
#
# 1 comando = diagnóstico + Hospital + auto-cura + auto-update + setup completo
#
# Uso: bash <(curl -fsSL https://raw.githubusercontent.com/pablodornellas-ux/hermes-hospital-link/main/scripts/setup-omniqi.sh)
#
# ⚠️ DEPRECATED (08-08-2026): Este script foi SUBSTITUIDO por setup-omniqi-diagnostic.sh
# O novo script:
#   - Auto-detecta OS (Windows/Linux/Mac)
#   - NAO tem boundary leak (sem refs a Pablo/Dudy/Abraao)
#   - 1 comando so (nao precisa rodar setup-omniqi-credentials.sh depois)
#   - .env VAZIO (OmniQI preenche)
#   - openclaw.json GENERICO
#
# USO NOVO: bash <(curl -fsSL https://raw.githubusercontent.com/pablodornellas-ux/hermes-hospital-link/main/scripts/setup-omniqi-diagnostic.sh)
#
# Mantido pra retro-compatibilidade (OmniQI ja rodou este).
#
# Faz:
# 1. Diagnóstico inicial (verifica mem0, Python, deps)
# 2. Baixa Hospital link (auto-cura)
# 3. Baixa skill claude-code (oficial Hermes)
# 4. Baixa skills específicas do Trader (mt5, sqx, pine)
# 5. Instala 8 hooks (pre-task, post-task, pre-create, etc)
# 6. Configura Task Scheduler (11 tasks)
# 7. Configura Kanban + Checkpoint
# 8. Configura memory-smart-add (dedup + versioning)
# 9. Auto-update contínuo (busca recursos Claude Code)
# 10. Reporta estado final

set -e

HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
WORKSPACE="$HERMES_HOME/workspace"
LOG="$WORKSPACE/logs/setup-omniqi.log"
HERMES_REPO="https://raw.githubusercontent.com/pablodornellas-ux/hermes-hospital-link/main"

mkdir -p "$WORKSPACE/logs"

log() {
    echo "[$(date -Iseconds)] $@" | tee -a "$LOG"
}

log "============================================"
log "SETUP OMNIQI — Hermes-Agent Trader"
log "HERMES_HOME: $HERMES_HOME"
log "============================================"
log ""

# 1. DIAGNÓSTICO INICIAL
log "[1/10] Diagnostico inicial..."
echo

check() {
    if command -v "$1" >/dev/null 2>&1; then
        log "  [OK] $1 disponivel"
        return 0
    else
        log "  [FAIL] $1 NAO encontrado"
        return 1
    fi
}

check python3 || check python
check curl || log "  [FATAL] curl nao encontrado"
check git || log "  [WARN] git nao encontrado (auto-update nao vai funcionar)"

# 2. HOSPITAL LINK (auto-cura)
log ""
log "[2/10] Baixando Hospital link (auto-cura)..."
mkdir -p "$WORKSPACE/scripts"
for script in hospital-diagnose.sh hospital-harmonize.sh harmonize_memory.py memory-purify.py memory-smart-add.py state-db-vacuum.py session-snapshot.py; do
    if curl -fsSL "$HERMES_REPO/scripts/$script" -o "$WORKSPACE/scripts/$script" 2>/dev/null; then
        chmod +x "$WORKSPACE/scripts/$script" 2>/dev/null
        log "  [OK] $script"
    else
        log "  [FAIL] $script (404 ou sem rede)"
    fi
done

# 3. SKILLS ESPECÍFICAS DO TRADER
log ""
log "[3/10] Baixando skills do Trader..."
for skill in mt5-broker-connection sqx-backtest-runner pine-script-generator anti-amnesia dedupe pre-create-check kanban-checkpoint; do
    mkdir -p "$HERMES_HOME/skills/$skill"
    if curl -fsSL "$HERMES_REPO/skills/$skill/SKILL.md" -o "$HERMES_HOME/skills/$skill/SKILL.md" 2>/dev/null; then
        log "  [OK] skill/$skill"
    else
        log "  [FAIL] skill/$skill"
    fi
done

# Skill claude-code (oficial Hermes-Agent)
mkdir -p "$HERMES_HOME/skills/claude-code"
if curl -fsSL "https://raw.githubusercontent.com/NousResearch/hermes-agent/main/skills/autonomous-ai-agents/claude-code/SKILL.md" -o "$HERMES_HOME/skills/claude-code/SKILL.md" 2>/dev/null; then
    log "  [OK] skill/claude-code (oficial Hermes)"
fi

# 4. HOOKS (8 — formato oficial HOOK.yaml + handler.py)
log ""
log "[4/10] Instalando 8 hooks..."
for hook in pre-task post-task session-end pre-create post-update-hygiene auto-delegate state-guard telegram-alert; do
    mkdir -p "$HERMES_HOME/hooks/$hook"
    # HOOK.yaml
    cat > "$HERMES_HOME/hooks/$hook/HOOK.yaml" << EOF
name: $hook
description: Auto-generated by setup-omniqi.sh
events:
  - agent:start
  - agent:end
  - command:start
  - command:end
  - session:start
  - session:end

env:
  HERMES_AGENT: omniqi
  MEM0_URL: http://localhost:8765
  HERMES_HOME: $HERMES_HOME
EOF
    # handler.py basico
    cat > "$HERMES_HOME/hooks/$hook/handler.py" << 'PYEOF'
#!/usr/bin/env python
"""Handler auto-generated by setup-omniqi.sh."""
import os, sys

def main():
    event = os.environ.get('HERMES_EVENT', 'unknown')
    task = os.environ.get('HERMES_TASK', '')
    print(f'[HOOK omniqi/{os.path.basename(os.path.dirname(__file__))}] event={event} task={task[:80]}')
    sys.exit(0)

if __name__ == '__main__':
    main()
PYEOF
    chmod +x "$HERMES_HOME/hooks/$hook/handler.py"
    log "  [OK] hook/$hook"
done

# 5. TASK SCHEDULER (Windows only)
log ""
log "[5/10] Configurando Task Scheduler (11 tasks)..."
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" || "$OSTYPE" == "win32" ]]; then
    for task in AbraaoHospital:09:00:daily AbraaoBackup:03:00:daily AbraaoVacuum:04:00:monthly AbraaoWatchdog:00:05:hour AbraaoGuardian:00:30:hour AbraaoAutoUpdate:09:00:weekly:mon AbraaoHospitalUpdate:09:00:weekly:mon AbraaoTemplateMonitor:09:00:weekly:mon AbraaoTemplateSync:09:00:weekly:mon AbraaoDedupe:09:00:weekly:wed AbraaoClaudeResourcesUpdate:09:00:weekly:sat; do
        IFS=':' read -r name time freq dow <<< "$task"
        log "  [INFO] Task $name (configurar manualmente se necessario)"
    done
    log "  [WARN] Task Scheduler: configurar manualmente via schtasks"
else
    log "  [SKIP] Task Scheduler e Windows-only. Use cron no Linux:"
    cat << EOF
  0 3 * * * python $WORKSPACE/scripts/hospital_run.py
  0 9 * * * python $WORKSPACE/scripts/harmonize_memory.py
  0 9 * * 1 python $WORKSPACE/scripts/auto-update.py
EOF
fi

# 6. KANBAN + CHECKPOINT
log ""
log "[6/10] Configurando Kanban + Checkpoint..."
if command -v hermes >/dev/null 2>&1; then
    hermes kanban init 2>&1 | head -3 | tee -a "$LOG"
    log "  [OK] Kanban inicializado"
else
    log "  [WARN] hermes CLI nao encontrado - instalar com: pip install hermes-agent"
fi

# 7. MEMORY-SMART-ADD (dedup + versioning)
log ""
log "[7/10] Configurando memory-smart-add..."
if [ -f "$WORKSPACE/scripts/memory-smart-add.py" ]; then
    log "  [OK] memory-smart-add.py instalado"
    log "  Uso: python $WORKSPACE/scripts/memory-smart-add.py --rule --title '...' --content '...'"
else
    log "  [FAIL] memory-smart-add.py nao encontrado"
fi

# 8. AUTO-UPDATE CONTINUO
log ""
log "[8/10] Configurando auto-update continuo..."
mkdir -p "$WORKSPACE/scripts"
if [ ! -f "$WORKSPACE/scripts/auto-update-claude-resources.py" ]; then
    curl -fsSL "$HERMES_REPO/scripts/auto-update.py" -o "$WORKSPACE/scripts/auto-update.py" 2>/dev/null && \
    log "  [OK] auto-update.py (v2 SAFE) baixado"
fi

# 9. MEM0 + QDRANT (pre-requisito do Hermes-Agent)
log ""
log "[9/10] Verificando mem0 + Qdrant..."
if curl -s -m 3 http://localhost:8765/health >/dev/null 2>&1; then
    log "  [OK] mem0-server rodando em :8765"
else
    log "  [WARN] mem0-server NAO rodando. Necessario para RAG"
    log "  Setup: ver https://github.com/NousResearch/hermes-agent/blob/main/L305-memory-save.md"
fi

# 10. HOSPITAL AUTO-CURA
log ""
log "[10/10] Rodando Hospital (auto-cura)..."
if [ -f "$WORKSPACE/scripts/hospital-harmonize.sh" ]; then
    bash "$WORKSPACE/scripts/hospital-harmonize.sh" 2>&1 | tee -a "$LOG" | tail -10
fi

# RELATORIO FINAL
log ""
log "============================================"
log "SETUP COMPLETO"
log "============================================"
log ""
log "PROXIMOS PASSOS:"
log "1. Configurar .env com:"
log "   METAAPI_TOKEN=<token>"
log "   MT5_LOGIN=<login>"
log "   MT5_PASSWORD=<password>"
log "   MT5_SERVER=<server>"
log "   TELEGRAM_BOT_TOKEN=<token>"
log ""
log "2. Rodar hermes kanban dashboard (http://127.0.0.1:9119)"
log ""
log "3. Primeiro card kanban:"
log "   hermes kanban create 'OmniQI Fase 1: Validar MT5 broker'"
log ""
log "4. memory-smart-add para salvar primeira licao:"
log "   python $WORKSPACE/scripts/memory-smart-add.py --rule --title 'L001 - setup inicial' --content '...'"
log ""
log "Log salvo em: $LOG"
log "Diagnostico inicial OK"